import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, NavLink, Link, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { API, normalizeJob, extractJobs, filterJobs, salary } from './jobs';
import './style.css';

function Icon({ name = 'arrow', size = 20 }) {
 const paths = { arrow: 'M4 12h16m-6-6 6 6-6 6', search: 'm21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0', pin: 'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0', bag: 'M3 7h18v14H3zM8 7V3h8v4M3 12h18M10 12v3h4v-3', check: 'm5 12 4 4L19 6', menu: 'M4 6h16M4 12h16M4 18h16', close: 'm6 6 12 12M6 18 18 6' };
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] || paths.arrow}/></svg>;
}
function Brand() { return <Link className="brand" to="/" aria-label="Langkah, beranda"><span className="brand-mark">L<span>↗</span></span>langkah<span className="brand-dot">.</span></Link>; }
function Header() {
 const [open, setOpen] = useState(false); const { pathname } = useLocation();
 useEffect(() => { setOpen(false); window.scrollTo(0, 0); }, [pathname]);
 return <header className="header"><div className="container nav-wrap"><Brand/><button className="btn btn-ghost mobile-toggle" aria-label={open ? 'Tutup menu' : 'Buka menu'} aria-expanded={open} aria-controls="navigation" onClick={() => setOpen(!open)}><Icon name={open ? 'close' : 'menu'}/></button><nav id="navigation" className={open ? 'navigation open' : 'navigation'} aria-label="Navigasi utama"><NavLink to="/" end>Beranda</NavLink><NavLink to="/job-vacancy">Lowongan pekerjaan</NavLink><NavLink to="/about">Tentang kami</NavLink><Link className="btn btn-primary nav-cta" to="/job-vacancy">Temukan pekerjaan <Icon size={17}/></Link></nav></div></header>;
}
function Footer() { return <footer><div className="container footer-top"><div><Brand/><p>Langkah kecil hari ini.<br/>Peluang besar di masa depan.</p></div><div><span className="eyebrow">JELAJAHI</span><Link to="/">Beranda</Link><Link to="/job-vacancy">Lowongan pekerjaan</Link><Link to="/about">Tentang kami</Link></div><div className="footer-note"><span className="eyebrow">DIBUAT UNTUK MASA DEPANMU</span><p>Temukan kesempatan yang sesuai<br/>dengan kemampuan dan ambisimu.</p><span className="pill">Satu langkah lebih dekat ↗</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Langkah. Final Project ReactJS.</span><span>Wahyu Purnama Magribi</span></div></footer>; }
function useJobs(id) {
 const [state, setState] = useState({ data: id ? null : [], loading: true, error: '' }); const [version, setVersion] = useState(0);
 useEffect(() => {
  const controller = new AbortController(); let active = true;
  const timer = setTimeout(() => controller.abort(), 15000);
  setState({ data: id ? null : [], loading: true, error: '' });
  fetch(id ? `${API}/${encodeURIComponent(id)}` : API, { signal: controller.signal }).then(async response => {
   if (!response.ok) throw new Error(response.status === 404 ? 'Lowongan tidak ditemukan atau sudah dihapus.' : 'Data belum dapat dimuat. Silakan coba kembali.');
   const payload = await response.json();
   if (id) { const item = payload.data ?? payload; if (!item || !(item._id || item.id)) throw new Error('Lowongan tidak ditemukan.'); return normalizeJob(item); }
   return extractJobs(payload);
  }).then(data => { if (active) setState({ data, loading: false, error: '' }); }).catch(error => { if (active) setState({ data: id ? null : [], loading: false, error: error.name === 'AbortError' ? 'Koneksi terlalu lama. Periksa internet dan coba kembali.' : error.message }); }).finally(() => clearTimeout(timer));
  return () => { active = false; clearTimeout(timer); controller.abort(); };
 }, [id, version]);
 return { ...state, retry: () => setVersion(v => v + 1) };
}
function Loading() { return <div className="state" role="status"><span className="loading loading-spinner loading-lg"/><p>Memuat peluang untukmu…</p></div>; }
function ErrorState({ error, retry }) { return <div className="state" role="alert"><h3>Belum bisa memuat lowongan</h3><p>{error}</p><button className="btn btn-primary" onClick={retry}>Coba lagi</button></div>; }
function Logo({ job }) { const [failed, setFailed] = useState(false); return <div className="company-logo">{job.company_image_url && !failed ? <img src={job.company_image_url} alt={`Logo ${job.company_name}`} loading="lazy" referrerPolicy="no-referrer" onError={() => setFailed(true)}/> : <span>{job.company_name.slice(0, 2).toUpperCase()}</span>}</div>; }
function JobCard({ job }) { return <article className="card job-card"><div className="card-top"><Logo job={job}/><span className={`badge job-status ${job.job_status === 1 ? 'is-open' : ''}`}>{job.job_status === 1 ? 'Dibuka' : 'Ditutup'}</span></div><p className="company-name">{job.company_name}</p><h3><Link to={`/job-vacancy/${job.id}`}>{job.title}</Link></h3><p className="location"><Icon name="pin" size={16}/>{job.company_city}</p><div className="tags"><span>{job.job_type || 'Tipe belum tersedia'}</span><span>{job.job_tenure || 'Tenure belum tersedia'}</span></div><div className="card-bottom"><span>{salary(job)}</span><Link className="round-link" to={`/job-vacancy/${job.id}`} aria-label={`Lihat detail ${job.title}`}><Icon size={19}/></Link></div></article>; }
function SearchBox() { const [query, setQuery] = useState(''); const navigate = useNavigate(); return <form className="hero-search" onSubmit={event => { event.preventDefault(); navigate(`/job-vacancy?q=${encodeURIComponent(query.trim())}`); }}><Icon name="search"/><label className="sr-only" htmlFor="hero-query">Posisi, perusahaan, atau lokasi</label><input id="hero-query" value={query} onChange={e => setQuery(e.target.value)} placeholder="Posisi, perusahaan, atau lokasi"/><button className="btn btn-primary" type="submit">Cari lowongan <Icon size={18}/></button></form>; }
function Home({ jobs }) {
 const featured = jobs.data.filter(job => job.job_status === 1).slice(0, 6);
 return <><section className="hero-area"><div className="container hero-layout"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> SAATNYA LANGKAH BERIKUTNYA</span><h1>Karier impianmu,<br/>dimulai dari<br/><em>satu langkah.</em></h1><p>Jelajahi peluang baru, temukan tempat bertumbuh,<br className="desktop-break"/> dan mulai perjalanan karier yang berarti.</p><SearchBox/><div className="popular">Populer: {['Developer', 'Designer', 'Marketing'].map(item => <Link key={item} to={`/job-vacancy?q=${item}`}>{item}</Link>)}</div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-dot"/><div className="float-label"><span className="check-circle"><Icon name="check"/></span>Kesempatan baru menantimu</div><div className="career-board"><div className="board-heading"><span>YOUR NEXT CHAPTER</span><span>↗</span></div><h2>Let’s grow<br/>together.</h2><div className="steps"><span/><span/><span><svg viewBox="0 0 60 60" fill="none"><path d="M13 46 46 13M15 13h31v31" stroke="currentColor" strokeWidth="6"/></svg></span></div><div className="board-bottom"><span>AMBITION MEETS OPPORTUNITY</span><span>✳</span></div></div><div className="float-bottom"><span className="mini-icon"><Icon name="bag"/></span><div><strong>Ruang untuk bertumbuh</strong><small>Temukan peran yang tepat untukmu</small></div><span>↗</span></div></div></div></section><section className="value-strip"><div className="container value-items"><span><Icon name="search"/>Peluang dalam satu tempat</span><span><Icon name="pin"/>Berbagai lokasi & cara kerja</span><span><Icon name="bag"/>Informasi karier yang terbuka</span></div></section><section className="container section"><div className="section-heading"><div><span className="eyebrow">TEMUKAN KESEMPATANMU</span><h2>Peran baru. Cerita baru.</h2><p>Pilihan lowongan terbuka untuk langkah berikutnya.</p></div><Link className="text-link" to="/job-vacancy">Lihat semua lowongan <Icon/></Link></div>{jobs.loading ? <Loading/> : jobs.error ? <ErrorState {...jobs}/> : featured.length ? <div className="job-grid">{featured.map(job => <JobCard job={job} key={job.id}/>)}</div> : <div className="state">Belum ada lowongan yang dibuka saat ini.</div>}</section><section className="container"><div className="callout"><div><span className="eyebrow">MASA DEPANMU MASIH PANJANG</span><h2>Temukan tempat terbaik<br/>untuk potensi besarmu.</h2><p>Kesempatan berikutnya bisa dimulai di sini.</p></div><Link className="btn lime-button" to="/job-vacancy">Jelajahi lowongan <Icon/></Link><span className="callout-star" aria-hidden="true">✳</span></div></section></>;
}
function Jobs({ jobs }) {
 const [params, setParams] = useSearchParams(); const query = params.get('q') || '', city = params.get('city') || '', type = params.get('type') || '', status = params.get('status') || ''; const [page, setPage] = useState(1);
 const update = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next, { replace: true }); setPage(1); };
 const filtered = useMemo(() => filterJobs(jobs.data, { query, city, type, status }), [jobs.data, query, city, type, status]);
 const cities = [...new Map(jobs.data.map(j => [j.company_city.toLowerCase(), j.company_city])).values()].sort(); const types = [...new Set(jobs.data.map(j => j.job_type).filter(Boolean))].sort();
 const pageCount = Math.max(1, Math.ceil(filtered.length / 9)); const current = Math.min(page, pageCount);
 useEffect(() => { setPage(1); }, [query, city, type, status]);
 return <><section className="page-banner"><div className="container"><span className="eyebrow">SATU PENCARIAN, BANYAK KEMUNGKINAN</span><h1>Temukan peluangmu.</h1><p>Peran yang tepat, di tempat yang tepat. Mulai jelajahi sekarang.</p></div></section><section className="container section"><div className="filter-panel"><label className="search-filter"><span>Cari lowongan</span><div className="input input-bordered"><Icon name="search"/><input value={query} onChange={e => update('q', e.target.value)} placeholder="Posisi atau perusahaan"/></div></label><label htmlFor="filter-city"><span>Lokasi</span><select id="filter-city" className="select select-bordered" aria-label="Lokasi" value={city} onChange={e => update('city', e.target.value)}><option value="">Semua lokasi</option>{cities.map(c => <option key={c}>{c}</option>)}</select></label><label htmlFor="filter-type"><span>Cara kerja</span><select id="filter-type" className="select select-bordered" aria-label="Cara kerja" value={type} onChange={e => update('type', e.target.value)}><option value="">Semua cara kerja</option>{types.map(t => <option key={t}>{t}</option>)}</select></label><label htmlFor="filter-status"><span>Status</span><select id="filter-status" className="select select-bordered" aria-label="Status" value={status} onChange={e => update('status', e.target.value)}><option value="">Semua status</option><option value="1">Dibuka</option><option value="0">Ditutup</option></select></label></div><div className="results-heading"><p><strong>{filtered.length}</strong> lowongan ditemukan</p><button className="btn btn-ghost btn-sm" onClick={() => { setParams({}); setPage(1); }}>Reset filter ↺</button></div>{jobs.loading ? <Loading/> : jobs.error ? <ErrorState {...jobs}/> : filtered.length ? <><div className="job-grid">{filtered.slice((current - 1) * 9, current * 9).map(job => <JobCard key={job.id} job={job}/>)}</div><div className="pagination"><button className="btn" disabled={current === 1} onClick={() => setPage(current - 1)}>← Sebelumnya</button><span>Halaman {current} dari {pageCount}</span><button className="btn" disabled={current === pageCount} onClick={() => setPage(current + 1)}>Selanjutnya →</button></div></> : <div className="state"><Icon name="search" size={32}/><h2>Belum ada yang cocok</h2><p>Coba kata kunci lain atau reset filter untuk melihat semua peluang.</p></div>}</section></>;
}
function Detail() {
 const { id } = useParams(); const jobState = useJobs(id); const job = jobState.data;
 return <section className="container section detail-page"><Link className="text-link" to="/job-vacancy">← Kembali ke lowongan</Link>{jobState.loading ? <Loading/> : jobState.error ? <ErrorState {...jobState}/> : job && <><div className="detail-heading"><Logo job={job}/><div><p className="company-name">{job.company_name}</p><h1>{job.title}</h1><p className="location"><Icon name="pin" size={17}/>{job.company_city}</p></div><span className={`badge job-status ${job.job_status === 1 ? 'is-open' : ''}`}>{job.job_status === 1 ? 'Dibuka' : 'Ditutup'}</span></div><div className="detail-layout"><div className="detail-content"><h2>Deskripsi pekerjaan</h2><p>{job.job_description || 'Deskripsi belum dicantumkan oleh perusahaan.'}</p><h2>Kualifikasi</h2><p>{job.job_qualification || 'Kualifikasi belum dicantumkan oleh perusahaan.'}</p></div><aside className="detail-summary"><h2>Ringkasan lowongan</h2><dl><dt>Perusahaan</dt><dd>{job.company_name}</dd><dt>Lokasi</dt><dd>{job.company_city}</dd><dt>Cara kerja</dt><dd>{job.job_type || 'Belum dicantumkan'}</dd><dt>Jenis pekerjaan</dt><dd>{job.job_tenure || 'Belum dicantumkan'}</dd><dt>Rentang gaji</dt><dd>{salary(job)}</dd></dl><div className="info-note">{job.job_status === 1 ? 'Tertarik dengan posisi ini? Cari kanal karier resmi perusahaan untuk informasi pendaftaran. Lowongan ini tidak menyertakan tautan melamar.' : 'Lowongan ini sudah ditutup. Jelajahi posisi lain yang masih terbuka.'}</div><Link className="btn btn-primary" to="/job-vacancy?status=1">Lihat peluang lainnya <Icon size={17}/></Link></aside></div></>}</section>;
}
function About() { return <><section className="page-banner"><div className="container"><span className="eyebrow">TENTANG LANGKAH</span><h1>Setiap perjalanan hebat<br/>bermula dari satu langkah.</h1><p>Kami percaya setiap orang layak menemukan ruang untuk bertumbuh.</p></div></section><section className="container section about-layout"><div><span className="eyebrow">TUJUAN KAMI</span><h2>Mendekatkanmu dengan<br/>peluang berikutnya.</h2><p>Langkah membantu pencari kerja menjelajahi informasi lowongan dalam tampilan yang sederhana dan mudah digunakan. Mulai dari posisi, perusahaan, lokasi, hingga rentang gaji dan kualifikasi, semuanya dapat ditemukan dalam satu tempat.</p><p>Gunakan pencarian dan filter untuk menemukan peran yang sesuai dengan minatmu. Pelajari detailnya, lalu kunjungi kanal resmi perusahaan untuk melanjutkan perjalananmu.</p><Link className="btn btn-primary" to="/job-vacancy">Mulai langkahmu <Icon/></Link></div><div className="about-values">{[['01', 'Mudah dijelajahi', 'Informasi lowongan dalam kartu yang ringkas, dengan pencarian dan filter yang praktis.'], ['02', 'Informasi yang jelas', 'Lihat deskripsi, kualifikasi, lokasi, status, dan rentang gaji sebelum menentukan pilihan.'], ['03', 'Di mana pun kamu berada', 'Jelajahi peluang dengan nyaman melalui ponsel, tablet, maupun komputer.']].map(([n,t,d]) => <article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section><section className="container project-note"><span className="eyebrow">TENTANG PROYEK</span><h3>Final Project — Web Frontend ReactJS (Level Menengah)</h3><p>Dibuat oleh Wahyu Purnama Magribi sebagai proyek pembelajaran Sanbercode. Aplikasi menggunakan React function components, React Hooks, React Router, Tailwind CSS, dan DaisyUI. Data berasal dari API lowongan yang disediakan dalam ketentuan tugas.</p><p>Langkah merupakan proyek pembelajaran dan bukan portal rekrutmen resmi perusahaan yang ditampilkan.</p></section></>; }
function NotFound() { return <section className="container state"><span className="eyebrow">404 — HALAMAN TIDAK DITEMUKAN</span><h1>Yuk, kembali ke jalurmu.</h1><p>Halaman yang kamu cari tidak tersedia.</p><Link className="btn btn-primary" to="/">Kembali ke beranda</Link></section>; }
function App() { const jobs = useJobs(); const { pathname } = useLocation(); useEffect(() => { document.title = `${pathname === '/' ? 'Temukan arah kariermu' : pathname === '/about' ? 'Tentang kami' : 'Lowongan pekerjaan'} — Langkah`; }, [pathname]); return <><a className="skip-link" href="#main">Lewati ke konten</a><Header/><main id="main"><Routes><Route path="/" element={<Home jobs={jobs}/>}/><Route path="/job-vacancy" element={<Jobs jobs={jobs}/>}/><Route path="/job-vacancy/:id" element={<Detail/>}/><Route path="/about" element={<About/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></>; }
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
